name: "Comprueba cómo se han cerrado los issues"
on:
  pull_request:
    paths:
      - 'proyectos/hito-[1234567].md'

jobs:
  closing_issue_check:
    runs-on: ubuntu-latest
    steps:
      - name: Extrae URL del repositorio
        uses: JJ/github-pr-contains-action@releases/v1
        with:
          github-token: ${{github.token}}
          filesChanged: 1
      - name: Busca eventos de cierre
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const diff = process.env.diff;
            const ghRepoMatch = /github.com\/(\S+)\/(.+?)(:\s+|\))/.exec(diff)
            if  ( ghRepoMatch === null ) {
                core.setFailed("❌ There's no repo URL in this diff with required format")
            } else {
                const user = ghRepoMatch[1] // segundo resultado
                const repo = ghRepoMatch[2] // tercer resultado
                console.log( "» Retrieving repo " + repo + " for user " + user )
                const non_paginated_issues = await github.issues.listForRepo.endpoint.merge( { owner: user,
                                                                                               repo: repo,
                                                                                               state: "closed" } )
                const issues = await github.paginate( non_paginated_issues )
                issues.forEach( async function( issue ) {
                    if ( ! issue.pull_request ) {
                        const query = `query($owner:String!, $name:String!, $issue:Int!) {
                            repository(name: $name , owner: $owner  ) {
                              issue(number: $issue) {
                                timelineItems(itemTypes: CLOSED_EVENT, last: 1) {
                                  nodes {
                                    ... on ClosedEvent {
                                      closer {
                                        __typename 
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }`;

                        const variables = {
                          owner: user,
                          name: repo,
                          issue: issue.number
                        }
                        const result = await github.graphql(query, variables)
                        const closingEvent = result.repository.issue.timelineItems.nodes[0].closer.__typename
                        if ( (closingEvent == 'Commit') || (closingEvent == 'PullRequest') ) {
                            console.log(" ✅ El issue " + issue.number + " se cerró con un " + closingEvent )
                        } else {
                            core.setFailed( "❌ El issue " + issue.number + " no se cerró con un commit o PR")
                        }
                  }
                })

            }

